### ISSUE TITLE
Multi concept benchmarking

### ISSUE THREAD

**Issue by ajikmr** [TIGER-AI-Lab/ImagenHub#15]
Hello.

Thanks for creating this repo.

Multi concept case is not working. It is not referenced properly in 'benchmarking.py' file.

I was able to run it after making few fixes. It will be great if you could take a look at it.

Thanks,
Ajitabh

**Comment by vinesmsuic** [comment]
Hi, can you elaborate more on the issue and how you fix it on your side?

**Comment by vinesmsuic** [comment]
I will look into it this month.

**Comment by vinesmsuic** [comment]
Fixed at [bbe44d3](https://github.com/TIGER-AI-Lab/ImagenHub/commit/bbe44d308ba52a11b619905d9d08179f4f27a04e)
