### ISSUE TITLE
Unicontrol call - Image to PIL.Image

### ISSUE THREAD

**Issue by ajikmr** [TIGER-AI-Lab/ImagenHub#17]
'Unicontrol.infer_one_image' call has a small bug.  

in line 102 of file 'src/imagen_hub/infermodels/unicontrol.py':

img = **Image**.fromarray(x_sample.astype(np.uint8))
_change to_ 
img = **PIL.Image**.fromarray(x_sample.astype(np.uint8))

Thanks.

**Comment by vinesmsuic** [comment]
Thanks
