### ISSUE TITLE
Is the per category raw data of human annotations going to be available?

### ISSUE THREAD

**Issue by kyleliang919** [TIGER-AI-Lab/ImagenHub#20]
As shown here the generation,
https://chromaica.github.io/Museum/ImagenHub_Text-Guided_IG/

We wish to study how humans actually decide what is better.

**Comment by vinesmsuic** [comment]
Thanks for the interest,

We just released the raw human annotation in https://github.com/TIGER-AI-Lab/ImagenHub/tree/main/eval/human_ratings.
