### ISSUE TITLE
About Image Editing Dataset prompts

### ISSUE THREAD

**Issue by h6kplus** [TIGER-AI-Lab/ImagenHub#22]
Nice work! I have a concern about the image editing benchmark which is the lack of "blend word" or the "subject word" that identify the object in the text prompt. For image editing models like prompt2prompt, cyclediffusion and the following line of work, they need a "blend word" to constrain the editing process while it's not provided in the editing dataset. Is it possible to add the blend words to the dataset?

**Comment by vinesmsuic** [comment]
Hi, can you clarify it a bit for "Is it possible to add the blend words to the dataset?"

The text-guided image editing benchmark is mainly designed for real-life edit scenarios. It does contain some object swapping prompts, but most of them were about adding and removing stuffs.
