### ISSUE TITLE
Border Lines in Image Masks

### ISSUE THREAD

**Issue by galmog** [TIGER-AI-Lab/ImagenHub#27]
**Describe the bug**
It seems that most if not all of the mask images in the mask-guided image editing dataset contain a sort of border line around the area of the mask. Meaning - the binary mask region (which is white in the region to be edited) contains a faint black line near the edge of the mask area. This results in weird behaviour in the editing process as the editing region is not continuous. The edited images have a very clear demarcation of where the edit mask was, which is not ideal and gives very unatural results. This is evident in the visualization website you provide as well.

**Expected behavior**
I'm not sure if this is intentional, but I would expect the provided masks in your dataset to be a single, continuous binary mask without this thin border.

**Example**

Original image:
![sample_17320_1](https://github.com/TIGER-AI-Lab/ImagenHub/assets/46827551/a88080f2-dd72-4257-9ab3-3312688453b4)
Mask image:
![17320_1_mask1](https://github.com/TIGER-AI-Lab/ImagenHub/assets/46827551/09e05fee-4999-4cb0-8116-aa7d8f624e18)
Edited image with an obvious border around the mask:
![17320_1_1](https://github.com/TIGER-AI-Lab/ImagenHub/assets/46827551/6e07690e-f46a-41ac-9214-96e1a92f3899)

**Comment by vinesmsuic** [comment]
Thanks for the catch! The masks were extracted from the [MagicBrush dataset](https://osu-nlp-group.github.io/MagicBrush/) so I just let the masks as it was. In fact, you can further process the mask with closing operation. This should make the mask more smooth without border issue. PR is welcomed.
![image](https://github.com/TIGER-AI-Lab/ImagenHub/assets/34955859/30c1daff-0636-4373-be7d-af49ac33a186)
